export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
EZA_ENABLE_SORT_ALIASES=1
EZA_ENABLE_EXTENDED_ALIASES=1
plugins=(git fzf golang helm kind kubectl aliases docker history terraform brew common-aliases eza)
source $ZSH/oh-my-zsh.sh

export PATH="${HOME}/bin:${PATH}"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [ -d "${HOME}/.config/zsh/zshrc.d" ]; then
        for rc in $(ls ${HOME}/.config/zsh/zshrc.d/); do
                echo "Loading ${HOME}/.config/zsh/zshrc.d/${rc}..."
                source ${HOME}/.config/zsh/zshrc.d/${rc}
        done
fi

export PATH="/home/pschwartz/bin:$PATH"

# . "$HOME/.local/bin/env"
